apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: uploads-pvc
    namespace: portfoliov3-api
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
